name: 'Dotnet Build and Test'
description: 'Builds a .NET project, runs tests and handles EF Core migrations including rollback on failure'
author: Mario De Benedictis

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  milliseconds:
    description: Your input description here
    required: true
    default: '1000'
  testFolder:
    description: 'Relative path to the test project folder'
    required: true
    default: 'YourTestFolderHere'   

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js

